# Generated by Django 5.1.1 on 2024-10-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0009_store_owner_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="button_link",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="button_text",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="tagline",
            field=models.CharField(blank=True, default="", max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
