# Generated by Django 5.1.1 on 2024-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "quickcommerce",
            "0010_alter_banner_button_link_alter_banner_button_text_and_more",
        ),
    ]

    operations = [
         migrations.RemoveField(
            model_name="order",
            name="id",
        ),
          migrations.RemoveField(
            model_name="orderitem",
            name="id",
        ),
       
    ]
