# Generated by Django 5.1.1 on 2024-12-03 06:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0011_order_order_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
       
       migrations.AddField(
            model_name="orderitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        
    ]
