# Generated by Django 5.1.1 on 2024-12-03 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0012_order_id_order_order_no"),
    ]

    operations = [
         migrations.RemoveField(
            model_name="orderitem",
            name="id",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
