# Generated by Django 5.1.1 on 2024-12-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0013_order_order_no"),
        ("quickcommerce", "0014_order_order_no"),
    ]

    operations = []
