# Generated by Django 5.1.1 on 2024-12-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0015_merge_0013_order_order_no_0014_order_order_no"),
    ]

    operations = [
       
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="inventory_software",
            field=models.CharField(
                choices=[
                    ("excel", "Excel"),
                    ("unicommerce", "UniCommerce"),
                    ("sap_hana", "SAP HANA"),
                    ("logicerp", "LogicERP"),
                    ("wizapp", "Wizapp"),
                ],
                max_length=255,
            ),
        ),
    ]
